variables:
  DOCKER_BUILDKIT: 0

default:
  tags:
    - aws-edgez-prd-k8s

include:
  - component: gitlab.netlight.com/components/opentofu/validate-plan-apply@2.6.1
    inputs:
      opentofu_version: 1.9.1
      root_dir: infra
      job_name_prefix: "aws-"
  - component: $CI_SERVER_FQDN/components/docker-build/buildkit@1.2.0
    inputs:
      tags: aws-edgez-prd-k8s
      name: simplesim-backend
      job_prefix: backend-
      dockerfile: Dockerfile.backend
      environment: prod
  - component: $CI_SERVER_FQDN/components/docker-build/buildkit@1.2.0
    inputs:
      tags: aws-edgez-prd-k8s
      name: simplesim-frontend
      job_prefix: frontend-
      dockerfile: Dockerfile.frontend
      environment: prod

stages: [validate, build, test, deploy]

deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - |
      # Replace CI_COMMIT_SHORT_SHA in deployment files
      sed -i "s/\${CI_COMMIT_SHORT_SHA}/$CI_COMMIT_SHORT_SHA/g" k8s/backend-deployment.yaml
      sed -i "s/\${CI_COMMIT_SHORT_SHA}/$CI_COMMIT_SHORT_SHA/g" k8s/frontend-deployment.yaml
      
      echo "Updated backend deployment:"
      cat k8s/backend-deployment.yaml
      echo "Updated frontend deployment:"
      cat k8s/frontend-deployment.yaml
      
      # Check kubectl access and context
      echo "Current kubectl context:"
      kubectl config current-context || echo "No current context"
      
      echo "Available contexts:"
      kubectl config get-contexts || echo "No contexts available"
      
      echo "Cluster info:"
      kubectl cluster-info || echo "Cannot get cluster info"
      
      # Try to apply deployments
      echo "Applying backend deployment..."
      kubectl apply -f k8s/backend-deployment.yaml
      
      echo "Applying frontend deployment..."
      kubectl apply -f k8s/frontend-deployment.yaml
      
      # Check deployment status
      echo "Checking backend deployment status..."
      kubectl rollout status deployment/simplesim-backend -n simplesim
      
      echo "Checking frontend deployment status..."
      kubectl rollout status deployment/simplesim-frontend -n simplesim
  tags:
    - aws-edgez-prd-k8s
  only:
    - main
    - master
