variables:
  DOCKER_BUILDKIT: 0
  # Use commit SHA for image tagging
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

default:
  tags:
    - aws-edgez-prd-k8s

include:
  - component: gitlab.netlight.com/components/opentofu/validate-plan-apply@2.6.1
    inputs:
      opentofu_version: 1.9.1
      root_dir: infra
      job_name_prefix: "aws-"
  - component: $CI_SERVER_FQDN/components/docker-build/buildkit@1.2.0
    inputs:
      tags: aws-edgez-prd-k8s
      name: simplesim-backend
      job_prefix: backend-
      dockerfile: Dockerfile.backend
      environment: prod
      # Use tag parameter instead of image_tag
      tag: $CI_COMMIT_SHORT_SHA
  - component: $CI_SERVER_FQDN/components/docker-build/buildkit@1.2.0
    inputs:
      tags: aws-edgez-prd-k8s
      name: simplesim-frontend
      job_prefix: frontend-
      dockerfile: Dockerfile.frontend
      environment: prod
      # Use tag parameter instead of image_tag
      tag: $CI_COMMIT_SHORT_SHA

stages: [validate, build, test, deploy]

# Add a deployment job that uses the commit SHA
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Deploying SimpleSim with commit SHA: $CI_COMMIT_SHORT_SHA"
    - echo "Backend image: simplesim-backend:$CI_COMMIT_SHORT_SHA"
    - echo "Frontend image: simplesim-frontend:$CI_COMMIT_SHORT_SHA"
    # Add deployment logic here if needed
  only:
    - main
    - master
