variables:
  DOCKER_BUILDKIT: 0

default:
  tags:
    - aws-edgez-prd-k8s

include:
  - component: gitlab.netlight.com/components/opentofu/validate-plan-apply@2.6.1
    inputs:
      opentofu_version: 1.9.1
      root_dir: infra
      job_name_prefix: "aws-"
  - component: $CI_SERVER_FQDN/components/docker-build/buildkit@1.2.0
    inputs:
      tags: aws-edgez-prd-k8s
      name: simplesim-backend
      job_prefix: backend-
      dockerfile: Dockerfile.backend
      environment: prod
  - component: $CI_SERVER_FQDN/components/docker-build/buildkit@1.2.0
    inputs:
      tags: aws-edgez-prd-k8s
      name: simplesim-frontend
      job_prefix: frontend-
      dockerfile: Dockerfile.frontend
      environment: prod
  - component: gitlab.netlight.com/components/kubernetes/apply@1.0.0
    inputs:
      job_prefix: k8s-
      manifests_dir: k8s
      environment: prod

stages: [validate, build, test, deploy]

.deploy-template:
  stage: deploy
  script:
    - |
      # Replace CI_COMMIT_SHORT_SHA in deployment files
      sed -i "s/\${CI_COMMIT_SHORT_SHA}/$CI_COMMIT_SHORT_SHA/g" k8s/backend-deployment.yaml
      sed -i "s/\${CI_COMMIT_SHORT_SHA}/$CI_COMMIT_SHORT_SHA/g" k8s/frontend-deployment.yaml
      
      echo "Updated backend deployment:"
      cat k8s/backend-deployment.yaml
      echo "Updated frontend deployment:"
      cat k8s/frontend-deployment.yaml
  tags:
    - aws-edgez-prd-k8s
  only:
    - main
    - master
