apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplesim-frontend
  namespace: simplesim
  labels:
    app: simplesim-frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplesim-frontend
  template:
    metadata:
      labels:
        app: simplesim-frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/simplesim-frontend@sha256:${IMAGE_DIGEST}
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
