apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplesim-frontend
  namespace: simplesim
  labels:
    app: simplesim-frontend
    version: v1
  annotations:
    kubectl.kubernetes.io/restartedAt: "2024-03-19T23:55:00Z"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplesim-frontend
  template:
    metadata:
      labels:
        app: simplesim-frontend
        version: v1
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-03-19T23:55:00Z"
    spec:
      nodeSelector:
        node-type: "x86-spot"
        capacity-type: "spot"
      tolerations:
        - key: "karpenter.sh/capacity-type"
          operator: Equal
          value: "spot"
          effect: NoSchedule
        - key: "kubernetes.io/arch"
          operator: Equal
          value: "amd64"
          effect: NoSchedule
        - key: "node-type"
          operator: Equal
          value: "x86-spot"
          effect: NoSchedule
      containers:
        - name: frontend
          image: 723216754178.dkr.ecr.eu-west-1.amazonaws.com/simplesim-frontend:c444f7ec
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
