apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simplesim-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.netlight.com/andreas.blomqvist/simple-simulation.git
    targetRevision: v1.3.0
    path: k8s
    directory:
      recurse: true
      include: "*.yaml"
      exclude: "oauth2.yaml"
  destination:
    server: https://3150EB617F71A130106643976A27E606.gr7.eu-west-1.eks.amazonaws.com
    namespace: simplesim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10 