"""
CORRECTED Role Business Rules - Based on Actual Business Model

Corrected role definitions based on the actual SimpleSim business model:
- Only CONSULTANTS are billable and generate revenue  
- Sales, Recruitment, Operations are support roles with NO direct revenue
- Revenue is generated by Consultant billable hours only
"""

# CORRECTED Role business rule definitions
CORRECTED_ROLE_DEFINITIONS = {
    'Consultant': {
        'billable': True,
        'has_levels': True,
        'levels': ['A', 'AC', 'C', 'SrC', 'M'],
        'progression_enabled': True,
        'revenue_model': 'billable_hours',
        'generates_revenue': True,         # Only Consultants generate revenue
        'utilization_tracked': True
    },
    'Sales': {
        'billable': False,
        'has_levels': True, 
        'levels': ['A', 'AC', 'C'],
        'progression_enabled': True,
        'revenue_model': 'support_role',   # CORRECTED: Support role, no revenue
        'generates_revenue': False,        # CORRECTED: Sales generates NO revenue
        'utilization_tracked': False
    },
    'Recruitment': {
        'billable': False,
        'has_levels': True,
        'levels': ['A', 'AC', 'C'], 
        'progression_enabled': True,
        'revenue_model': 'support_role',   # CORRECTED: Support role, no revenue
        'generates_revenue': False,        # CORRECTED: Recruitment generates NO revenue
        'utilization_tracked': False
    },
    'Operations': {
        'billable': False,
        'has_levels': False,
        'levels': ['Operations'],
        'progression_enabled': False,
        'revenue_model': 'support_role',   # CORRECTED: Support role, no revenue
        'generates_revenue': False,        # CORRECTED: Operations generates NO revenue
        'utilization_tracked': False
    }
}

def calculate_corrected_role_financial_kpis(role_kpis, business_plan_targets):
    """
    CORRECTED: Calculate financial KPIs with proper revenue attribution
    
    BUSINESS MODEL:
    - ALL revenue comes from Consultant billable hours
    - Sales, Recruitment, Operations are pure cost centers
    - Total office revenue is distributed only to revenue-generating roles (Consultants)
    """
    
    financial_kpis = {}
    
    # Get total revenue and costs from business plan
    total_revenue = business_plan_targets.revenue_target
    total_costs = business_plan_targets.operating_costs
    
    # Calculate revenue-generating workforce (ONLY Consultants)
    consultant_headcount = role_kpis['Consultant']['total_headcount']
    total_headcount = sum(kpi['total_headcount'] for kpi in role_kpis.values())
    
    # CORRECTED: Revenue attribution
    for role, role_kpi in role_kpis.items():
        role_definition = CORRECTED_ROLE_DEFINITIONS[role]
        role_headcount = role_kpi['total_headcount']
        
        # Revenue attribution by role type
        if role_definition['generates_revenue']:
            # ONLY Consultants get revenue attribution (all of it)
            role_revenue = total_revenue
            role_revenue_type = 'billable_hours'
            
        else:
            # Sales, Recruitment, Operations generate ZERO revenue
            role_revenue = 0
            role_revenue_type = 'support_role'
        
        # Cost allocation (distribute costs by headcount)
        role_costs = (role_headcount / total_headcount * total_costs) if total_headcount > 0 else 0
        
        role_financial = {
            'role': role,
            'revenue_model': role_revenue_type,
            'revenue': role_revenue,
            'costs': role_costs,
            'profit': role_revenue - role_costs,
            'profit_margin_pct': ((role_revenue - role_costs) / role_revenue * 100) if role_revenue > 0 else 0,
            'revenue_per_fte': role_revenue / role_headcount if role_headcount > 0 else 0,
            'cost_per_fte': role_costs / role_headcount if role_headcount > 0 else 0,
            'generates_revenue': role_definition['generates_revenue']
        }
        
        financial_kpis[role] = role_financial
    
    return financial_kpis

# Example corrected output:
def show_corrected_financial_structure():
    """Show the corrected financial KPI structure"""
    
    example_corrected_structure = {
        'role_specific_financial': {
            'Consultant': {
                'revenue_model': 'billable_hours',
                'revenue': 587284,              # Gets ALL office revenue
                'costs': 257901,                # Proportional costs
                'profit': 329383,
                'generates_revenue': True       # Only role that generates revenue
            },
            'Sales': {
                'revenue_model': 'support_role',
                'revenue': 0,                   # CORRECTED: NO revenue
                'costs': 128951,                # Pure cost center
                'profit': -128951,              # Expected cost
                'generates_revenue': False      # CORRECTED: Support role
            },
            'Recruitment': {
                'revenue_model': 'support_role', 
                'revenue': 0,                   # CORRECTED: NO revenue
                'costs': 24178,                 # Pure cost center
                'profit': -24178,               # Expected cost
                'generates_revenue': False      # CORRECTED: Support role
            },
            'Operations': {
                'revenue_model': 'support_role',
                'revenue': 0,                   # CORRECTED: NO revenue
                'costs': 16119,                 # Pure cost center
                'profit': -16119,               # Expected cost
                'generates_revenue': False      # CORRECTED: Support role
            }
        }
    }
    
    return example_corrected_structure

if __name__ == "__main__":
    print("CORRECTED Role Business Rules")
    print("=" * 35)
    
    print("\\nRevenue Generation:")
    for role, definition in CORRECTED_ROLE_DEFINITIONS.items():
        revenue_status = "✅ GENERATES REVENUE" if definition['generates_revenue'] else "❌ Cost Center"
        print(f"   {role}: {revenue_status}")
    
    print("\\nBusiness Model:")
    print("   • Consultants: Generate ALL office revenue through billable hours")
    print("   • Sales: Support role - NO revenue generation")  
    print("   • Recruitment: Support role - NO revenue generation")
    print("   • Operations: Support role - NO revenue generation")
    
    print("\\nCORRECTED Financial KPI Structure:")
    structure = show_corrected_financial_structure()
    
    consultant_kpis = structure['role_specific_financial']['Consultant']
    sales_kpis = structure['role_specific_financial']['Sales']
    
    print(f"   Consultant: ${consultant_kpis['revenue']:,} revenue, ${consultant_kpis['costs']:,} costs")
    print(f"   Sales: ${sales_kpis['revenue']:,} revenue, ${sales_kpis['costs']:,} costs")
    print(f"   Recruitment: $0 revenue (support role)")
    print(f"   Operations: $0 revenue (support role)")